//! Init instruction handler

use {
    crate::{
        error::SkyTradeError,
        state::{airspace::Airspace, configs::Configs, deposit_base::DepositBase},
    },
    anchor_lang::prelude::*,
    //anchor_spl::token::{Token, TokenAccount},
    //solana_program::program_error::ProgramError,
};

#[derive(Accounts)]
#[instruction(params: InitParams)]
pub struct Init<'info> {
    // init means to create account
    // bump to use unique address for account
    #[account(
        init,
        payer = owner,
        space = 8 + Configs::INIT_SPACE,
        constraint = !configs.is_initialized @ SkyTradeError::AccountAlreadyInitialized,
        seeds = [b"configs"],
        bump
    )]
    pub configs: Account<'info, Configs>,
    #[account(
        init,
        payer = owner,
        space = 8 + Airspace::INIT_SPACE,
        constraint = !configs.is_initialized @ SkyTradeError::AccountAlreadyInitialized,
        seeds = [b"airspace"],
        bump
    )]
    pub airspace: Account<'info, Airspace>,
    #[account(init, payer = owner, space = 8 + DepositBase::INIT_SPACE,
        constraint = !admin_deposit_account.is_initialized @ SkyTradeError::AccountAlreadyInitialized
    )]
    pub admin_deposit_account: Account<'info, DepositBase>,
    #[account(seeds = [b"admin-auth", admin_deposit_account.key().as_ref()], bump)]
    /// CHECK: no need to check this.
    pub admin_pda_auth: UncheckedAccount<'info>,
    #[account(mut, seeds = [b"admin-sol-vault", admin_pda_auth.key().as_ref()], bump)]
    pub admin_sol_vault: SystemAccount<'info>,
    // mut makes it changeble (mutable)
    #[account(mut)]
    pub owner: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct InitParams {
    // price per cubic foot. Used to calculate income
    // to be generated by property owner
    pub price_per_cubic_foot: u32,
    pub buying_price_per_cubic_foot: u32, // buying price per cubic foot
}

pub fn init(ctx: Context<Init>, params: &InitParams) -> Result<()> {
    msg!("Validate inputs");

    if params.price_per_cubic_foot == 0 {
        return Err(SkyTradeError::InvalidPricePerCubicFoot.into());
    }

    let deposit_account = &mut ctx.accounts.admin_deposit_account;
    let configs = &mut ctx.accounts.configs;
    let airspace = &mut ctx.accounts.airspace;

    // admin deposit account
    deposit_account.owner = *ctx.accounts.owner.key;
    deposit_account.admin_auth_bump = ctx.bumps.admin_pda_auth;
    deposit_account.admin_sol_vault_bump = Some(ctx.bumps.admin_sol_vault);
    deposit_account.is_initialized = true;

    // configs
    configs.price_per_cubic_foot = params.price_per_cubic_foot;
    configs.is_initialized = true;

    //airspace
    airspace.is_initialized = true;

    Ok(())
}
